### ISSUE TITLE
No Chrome Extension Template option in New Project dialog

### ISSUE THREAD

**Issue by exportio** [Codaflex/ChromeExtensionTemplate#1]
I followed the instructions but there is no Chrome Extension Template as an option in New Project dialog.   The "My Exported Templates" folder did not exist, so I created it and pasted the zip file inside.  I restarted VS and could not find the project type.

**Comment by MiroJ** [comment]
It worked the last time I did it. I will verify the process and let you know how it goes.

**Comment by MiroJ** [comment]
Apparently, the location of the folder where VS searches for custom templates has been moved. Now, it is `\Users\{your_user}\Documents\Visual Studio 2017\Templates\ProjectTemplates\`. I have updated the README file.
Thank you for catching that.
